package edu.heuet.shaohua.dao;

import edu.heuet.shaohua.dataobject.StudentDO;

import java.util.List;

public interface StudentDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_inf_mysql
     *
     * @mbg.generated Tue Jan 19 15:17:18 GMT+08:00 2021
     */
    int deleteByPrimaryKey(String studentNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_inf_mysql
     *
     * @mbg.generated Tue Jan 19 15:17:18 GMT+08:00 2021
     */
    int insert(StudentDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_inf_mysql
     *
     * @mbg.generated Tue Jan 19 15:17:18 GMT+08:00 2021
     */
    int insertSelective(StudentDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_inf_mysql
     *
     * @mbg.generated Tue Jan 19 15:17:18 GMT+08:00 2021
     */
    StudentDO selectByPrimaryKey(String studentNo);

    StudentDO selectByName(String name);

    List<StudentDO> getAll();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_inf_mysql
     *
     * @mbg.generated Tue Jan 19 15:17:18 GMT+08:00 2021
     */
    int updateByPrimaryKeySelective(StudentDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_inf_mysql
     *
     * @mbg.generated Tue Jan 19 15:17:18 GMT+08:00 2021
     */
    int updateByPrimaryKey(StudentDO record);
}