package edu.heuet.shaohua.dataobject;

import java.util.Date;

public class NewsDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_info.id
     *
     * @mbg.generated Wed Jun 17 23:26:31 GMT+08:00 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_info.title
     *
     * @mbg.generated Wed Jun 17 23:26:31 GMT+08:00 2020
     */
    private String title;

    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_info.picture
     *
     * @mbg.generated Wed Jun 17 23:26:31 GMT+08:00 2020
     */
    private String picture;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_info.create_time
     *
     * @mbg.generated Wed Jun 17 23:26:31 GMT+08:00 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_info.update_time
     *
     * @mbg.generated Wed Jun 17 23:26:31 GMT+08:00 2020
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_info.id
     *
     * @return the value of news_info.id
     *
     * @mbg.generated Wed Jun 17 23:26:31 GMT+08:00 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_info.id
     *
     * @param id the value for news_info.id
     *
     * @mbg.generated Wed Jun 17 23:26:31 GMT+08:00 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_info.title
     *
     * @return the value of news_info.title
     *
     * @mbg.generated Wed Jun 17 23:26:31 GMT+08:00 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_info.title
     *
     * @param title the value for news_info.title
     *
     * @mbg.generated Wed Jun 17 23:26:31 GMT+08:00 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_info.picture
     *
     * @return the value of news_info.picture
     *
     * @mbg.generated Wed Jun 17 23:26:31 GMT+08:00 2020
     */
    public String getPicture() {
        return picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_info.picture
     *
     * @param picture the value for news_info.picture
     *
     * @mbg.generated Wed Jun 17 23:26:31 GMT+08:00 2020
     */
    public void setPicture(String picture) {
        this.picture = picture == null ? null : picture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_info.create_time
     *
     * @return the value of news_info.create_time
     *
     * @mbg.generated Wed Jun 17 23:26:31 GMT+08:00 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_info.create_time
     *
     * @param createTime the value for news_info.create_time
     *
     * @mbg.generated Wed Jun 17 23:26:31 GMT+08:00 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_info.update_time
     *
     * @return the value of news_info.update_time
     *
     * @mbg.generated Wed Jun 17 23:26:31 GMT+08:00 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_info.update_time
     *
     * @param updateTime the value for news_info.update_time
     *
     * @mbg.generated Wed Jun 17 23:26:31 GMT+08:00 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}