package edu.heuet.shaohua.dataobject;

import java.util.Date;

public class StudentDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_inf_mysql.student_no
     *
     * @mbg.generated Tue Jan 19 15:17:18 GMT+08:00 2021
     */
    private String studentNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_inf_mysql.name
     *
     * @mbg.generated Tue Jan 19 15:17:18 GMT+08:00 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_inf_mysql.create_time
     *
     * @mbg.generated Tue Jan 19 15:17:18 GMT+08:00 2021
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_inf_mysql.update_time
     *
     * @mbg.generated Tue Jan 19 15:17:18 GMT+08:00 2021
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_inf_mysql.student_no
     *
     * @return the value of student_inf_mysql.student_no
     *
     * @mbg.generated Tue Jan 19 15:17:18 GMT+08:00 2021
     */
    public String getStudentNo() {
        return studentNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_inf_mysql.student_no
     *
     * @param studentNo the value for student_inf_mysql.student_no
     *
     * @mbg.generated Tue Jan 19 15:17:18 GMT+08:00 2021
     */
    public void setStudentNo(String studentNo) {
        this.studentNo = studentNo == null ? null : studentNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_inf_mysql.name
     *
     * @return the value of student_inf_mysql.name
     *
     * @mbg.generated Tue Jan 19 15:17:18 GMT+08:00 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_inf_mysql.name
     *
     * @param name the value for student_inf_mysql.name
     *
     * @mbg.generated Tue Jan 19 15:17:18 GMT+08:00 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_inf_mysql.create_time
     *
     * @return the value of student_inf_mysql.create_time
     *
     * @mbg.generated Tue Jan 19 15:17:18 GMT+08:00 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_inf_mysql.create_time
     *
     * @param createTime the value for student_inf_mysql.create_time
     *
     * @mbg.generated Tue Jan 19 15:17:18 GMT+08:00 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_inf_mysql.update_time
     *
     * @return the value of student_inf_mysql.update_time
     *
     * @mbg.generated Tue Jan 19 15:17:18 GMT+08:00 2021
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_inf_mysql.update_time
     *
     * @param updateTime the value for student_inf_mysql.update_time
     *
     * @mbg.generated Tue Jan 19 15:17:18 GMT+08:00 2021
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}